-- Game Teams table (replaced game_teams2)
CREATE TABLE IF NOT EXISTS "public"."game_teams" (
    "game_team_id" bigint NOT NULL,
    "bots" integer[] DEFAULT '{}'::integer[],
    "created_at" timestamp with time zone DEFAULT timezone('utc'::text, now())
);

ALTER TABLE "public"."game_teams" OWNER TO "postgres";

-- Primary key
ALTER TABLE ONLY "public"."game_teams" ADD CONSTRAINT "game_teams_pkey" PRIMARY KEY ("game_team_id");

-- Comments
COMMENT ON TABLE "public"."game_teams" IS 'Teams for a specific game instance';
COMMENT ON COLUMN "public"."game_teams"."bots" IS 'Array of bot IDs in the team';

-- Identity sequence for game_team_id
ALTER TABLE "public"."game_teams" ALTER COLUMN "game_team_id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."game_teams_game_team_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Enable RLS
ALTER TABLE "public"."game_teams" ENABLE ROW LEVEL SECURITY;

-- Grant access to anon and authenticated roles
GRANT ALL ON TABLE "public"."game_teams" TO "anon";
GRANT ALL ON TABLE "public"."game_teams" TO "authenticated";
GRANT ALL ON TABLE "public"."game_teams" TO "service_role";
